### ISSUE TITLE
Exception on ZRANGEBYSCORE

### ISSUE THREAD

**Issue by lstrojny** [spullara/redis-protocol#42]
The testsuite for solr-redis (https://github.com/sematext/solr-redis) yield the following exception on `ZRANGEBYSCORE`:

```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at redis.util.ZSet.subSet(ZSet.java:125)
    at redis.server.netty.SimpleRedisServer._zrangebyscore(SimpleRedisServer.java:2850)
    at redis.server.netty.SimpleRedisServer.zrevrangebyscore(SimpleRedisServer.java:3035)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at redis.server.netty.RedisCommandHandler$1.execute(RedisCommandHandler.java:44)
    at redis.server.netty.RedisCommandHandler.messageReceived(RedisCommandHandler.java:82)
    at redis.server.netty.RedisCommandHandler.messageReceived(RedisCommandHandler.java:25)
    at io.netty.channel.ChannelHandlerUtil.handleInboundBufferUpdated(ChannelHandlerUtil.java:60)
    at io.netty.channel.ChannelInboundMessageHandlerAdapter.inboundBufferUpdated(ChannelInboundMessageHandlerAdapter.java:100)
    at io.netty.channel.DefaultChannelHandlerContext.invokeInboundBufferUpdated(DefaultChannelHandlerContext.java:1031)
    at io.netty.channel.DefaultChannelHandlerContext.access$1500(DefaultChannelHandlerContext.java:39)
    at io.netty.channel.DefaultChannelHandlerContext$13.run(DefaultChannelHandlerContext.java:1005)
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:114)
    at java.lang.Thread.run(Thread.java:745)
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at redis.util.ZSet.subSet(ZSet.java:125)
    at redis.server.netty.SimpleRedisServer._zrangebyscore(SimpleRedisServer.java:2850)
    at redis.server.netty.SimpleRedisServer.zrevrangebyscore(SimpleRedisServer.java:3035)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at redis.server.netty.RedisCommandHandler$1.execute(RedisCommandHandler.java:44)
    at redis.server.netty.RedisCommandHandler.messageReceived(RedisCommandHandler.java:82)
    at redis.server.netty.RedisCommandHandler.messageReceived(RedisCommandHandler.java:25)
    at io.netty.channel.ChannelHandlerUtil.handleInboundBufferUpdated(ChannelHandlerUtil.java:60)
    at io.netty.channel.ChannelInboundMessageHandlerAdapter.inboundBufferUpdated(ChannelInboundMessageHandlerAdapter.java:100)
    at io.netty.channel.DefaultChannelHandlerContext.invokeInboundBufferUpdated(DefaultChannelHandlerContext.java:1031)
    at io.netty.channel.DefaultChannelHandlerContext.access$1500(DefaultChannelHandlerContext.java:39)
    at io.netty.channel.DefaultChannelHandlerContext$13.run(DefaultChannelHandlerContext.java:1005)
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:114)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by regina-work** [comment]
same here
why?
is there a fix? using redis-maven-plugin
